# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: "3.10"
        architecture: x64
        version: "2.7.4"
        prerelease: false
        enable-pep582: false
        allow-python-prereleases: false
    - name: Install dependencies
      run: pdm install --group all
    - name: Test with pytest
      run: |
        pdm run pytest
